# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cad6006423fe4d99d1f8883fb44669d6f7d67d2cef2131c7de85922f011c212713a3267f963b9877acf2605a42934c3d6e13ed1c06e37fc23d7400d2bbcec21

test:
  secret_key_base: 083f64d836a0d49f2e18998d16bcc0a01f7d2151a8ef829a3c9bfc1c3e2dd548bd99041272a16df71d6b39dcf5ceb657fcbfb7d867267283fb6391957dd66ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
